name: regular

# only run when triggered manually
on:
  workflow_dispatch:

jobs:
  regular:
    runs-on: ubuntu-latest
    container: cypress/base:24.12.0
    steps:
      - name: Checkout ğŸ›ï¸
        # https://github.com/actions/checkout
        uses: actions/checkout@v6

      - name: Cypress tests
        # https://github.com/cypress-io/github-action
        # installs everything and runs the tests
        uses: cypress-io/github-action@v6
